name: Keep Alive Render

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render instance
        run: curl -s https://api-consumet-org-qfhg.onrender.com/
